# Use postgres/example user/password credentials

services:

  db:
    image: postgres:16
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data 
    environment:
      POSTGRES_USER: logingo
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: yourdb

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_URL: postgres://logingo:mypassword@db:5432/mydb?sslmode=disable

volumes:
  pgdata:

networks:
  backend: