openapi: 3.0.4
info:
  title: LoginGO API
  description: An API to organize a login template
  version: 1.0.9


servers:
  - url: http://localhost:8080/

paths:
  /register:
    get:
      summary: Returns the HTML template to register
      description: Serves the registration page as HTML
      tags:
        - Pages    
      responses:
        "200":
          description: The HTML registration page
          content:
            text/html:
              schema:
                $ref: "#/components/schemas/User"
        "301":
          description: Moved permanently
        "400":
          description: Bad request
        "404":
          description: Not found
        "503":
          description: Service unavailable

    post:
      summary: Registers the user
      responses:
        "200":
          description: The HTML login page
          content:
            text/html:
              schema:
                $ref: "#/components/schemas/User"
        "301":
        "400":
        "404":
        "503":

  /login:
    get:
      summary: Returns the HTML template to login
      responses:
        "200":
        "301":
          description: Moved permanently
        "400":
          description: Bad request
        "404":
          description: Not found
        "503":
          description: Service unavailable

    post:
      summary: Logs in the user
      responses:
        "200":
        "301":
        "400":
        "404":
        "503":

  /logout:
    post:
      summary: Logs out the user
      responses:
        "200":
        "301":
          description: Moved permanently
        "400":
          description: Bad request
        "404":
          description: Not found
        "503":
          description: Service unavailable


components:
  schemas:
    User:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    
    Error: 
      type: object
      properties:
        code:
          type: integer
        message:
          type: string